### ~/VorlesungenUndPraktika/RZyklen/Daten/Spinaltumoren.R
### Die Daten zu Blutgruppe und Spinaltumorätiologie für Blatt 2
###**************************************************************************

Blutgruppe <- c(
 "B", "0", "0", "0", "A", "0", "0", "0", "0", "0", "A", "A", "0", "0", "0",
 "0", "0", "0", "A", "A", "B", "A", "A", "0", "A", "A", "A", "0", "0", "A",
 "A", "0", "0", "A", "0", "0", "A", "0", "A", "A", "A", "A", "A", "A", "A",
 "0", "A", "0", "A", "A", "AB", "B", "A", "A", "A", "0", "0", "B", "0", "A",
 "0", "A", "A", "0", "A", "AB", "AB", "0", "A", "A", "A", "B", "A", "0", "A",
 "A", "0", "A", "A", "A", "0", "0", "A", "A", "0", "0", "A", "B", "B", "0",
 "0", "B", "A", "0", "B", "A", "0", "0", "0", "0", "0", "0", "0", "0", "AB",
 "B", "B", "0", "B", "A", "A", "0", "A", "0", "A", "AB", "A", "A", "0", "A",
 "0", "A", "0", "B", "0", "A", "0", "A", "0", "A", "A", "A", "A", "A", "0",
 "0", "A", "0", "0", "0", "A", "A", "A", "B", "A", "A", "A", "B", "0", "A",
 "A", "B", "0", "0", "B", "B", "0", "A", "0", "A", "AB", "B", "0", "A", "0",
 "A", "0", "A", "A", "0", "AB", "A", "A", "A", "A", "0", "A", "0", "B", "0",
 "A", "AB", "AB", "A", "AB", "A", "0", "A", "A", "AB", "0", "0", "A", "B",
 "0", "A", "B", "0", "0", "B", "0", "0", "0", "0", "A", "A", "B", "A", "0",
 "0", "A", "0", "A", "0", "A", "A", "A", "0", "A", "A", "A", "A", "A", "0",
 "A", "A", "A", "0", "0", "A", "0", "B", "A", "0", "A", "A", "B", "0", "0",
 "0", "AB", "0", "A", "0", "AB", "A", "B", "0", "0", "A", "A", "0", "0", "A",
 "0", "AB", "AB", "A", "A", "A", "B", "0", "A", "B", "A", "0", "A", "A", "A",
 "A", "0", "A", "A", "B", "0", "0", "B", "A", "0", "0", "0", "0", "0", "A",
 "0", "0", "0", "0", "A", "0", "0", "A", "A", "A", "A", "0", "0", "A", "0",
 "A", "A", "0", "0", "0", "0", "B", "0", "B", "A", "A", "A", "A", "A", "0",
 "0", "0", "A", "A", "A", "AB", "A", "0", "0", "B")

Tumoraetiologie <- c(
 "Mesenchymal", "Sonstiges", "Mesenchymal", "Mesenchymal", "Metastase",
 "Mesenchymal", "Metastase", "Metastase", "Metastase", "Metastase",
 "Neuroepithelial", "Metastase", "Mesenchymal", "Metastase",
 "Neuroepithelial", "Nervenscheiden", "Sonstiges", "Metastase",
 "Nervenscheiden", "Metastase", "Metastase", "Neuroepithelial",
 "Nervenscheiden", "Mesenchymal", "Metastase", "Sonstiges", "Mesenchymal",
 "Neuroepithelial", "Mesenchymal", "Sonstiges", "Sonstiges", "Sonstiges",
 "Sonstiges", "Neuroepithelial", "Sonstiges", "Nervenscheiden",
 "Neuroepithelial", "Sonstiges", "Nervenscheiden", "Metastase", "Metastase",
 "Sonstiges", "Metastase", "Mesenchymal", "Metastase", "Nervenscheiden",
 "Sonstiges", "Metastase", "Mesenchymal", "Metastase", "Sonstiges",
 "Neuroepithelial", "Mesenchymal", "Mesenchymal", "Sonstiges", "Mesenchymal",
 "Mesenchymal", "Metastase", "Nervenscheiden", "Mesenchymal", "Sonstiges",
 "Neuroepithelial", "Nervenscheiden", "Nervenscheiden", "Metastase",
 "Mesenchymal", "Neuroepithelial", "Metastase", "Metastase", "Sonstiges",
 "Metastase", "Nervenscheiden", "Metastase", "Metastase", "Neuroepithelial",
 "Sonstiges", "Neuroepithelial", "Metastase", "Nervenscheiden", "Sonstiges",
 "Sonstiges", "Metastase", "Metastase", "Metastase", "Neuroepithelial",
 "Nervenscheiden", "Metastase", "Sonstiges", "Nervenscheiden", "Metastase",
 "Sonstiges", "Mesenchymal", "Metastase", "Metastase", "Metastase",
 "Sonstiges", "Sonstiges", "Metastase", "Neuroepithelial", "Mesenchymal",
 "Metastase", "Sonstiges", "Mesenchymal", "Neuroepithelial", "Sonstiges",
 "Metastase", "Metastase", "Metastase", "Mesenchymal", "Metastase",
 "Neuroepithelial", "Metastase", "Mesenchymal", "Nervenscheiden",
 "Mesenchymal", "Metastase", "Neuroepithelial", "Neuroepithelial",
 "Neuroepithelial", "Neuroepithelial", "Neuroepithelial", "Nervenscheiden",
 "Mesenchymal", "Metastase", "Nervenscheiden", "Mesenchymal", "Metastase",
 "Neuroepithelial", "Mesenchymal", "Neuroepithelial", "Mesenchymal",
 "Mesenchymal", "Metastase", "Sonstiges", "Neuroepithelial", "Metastase",
 "Metastase", "Metastase", "Sonstiges", "Metastase", "Metastase",
 "Sonstiges", "Nervenscheiden", "Metastase", "Nervenscheiden", "Sonstiges",
 "Neuroepithelial", "Mesenchymal", "Mesenchymal", "Metastase", "Metastase",
 "Metastase", "Metastase", "Metastase", "Nervenscheiden", "Metastase",
 "Nervenscheiden", "Mesenchymal", "Mesenchymal", "Sonstiges", "Sonstiges",
 "Metastase", "Mesenchymal", "Mesenchymal", "Neuroepithelial",
 "Mesenchymal", "Metastase", "Neuroepithelial", "Metastase",
 "Neuroepithelial", "Neuroepithelial", "Metastase", "Neuroepithelial",
 "Neuroepithelial", "Neuroepithelial", "Metastase", "Mesenchymal",
 "Mesenchymal", "Sonstiges", "Nervenscheiden", "Mesenchymal",
 "Mesenchymal", "Nervenscheiden", "Metastase", "Nervenscheiden",
 "Metastase", "Metastase", "Mesenchymal", "Metastase", "Nervenscheiden",
 "Metastase", "Nervenscheiden", "Sonstiges", "Metastase", "Mesenchymal",
 "Neuroepithelial", "Nervenscheiden", "Mesenchymal", "Sonstiges",
 "Sonstiges", "Metastase", "Sonstiges", "Nervenscheiden", "Metastase",
 "Metastase", "Nervenscheiden", "Neuroepithelial", "Metastase",
 "Sonstiges", "Sonstiges", "Sonstiges", "Sonstiges", "Mesenchymal",
 "Mesenchymal", "Metastase", "Metastase", "Sonstiges", "Nervenscheiden",
 "Sonstiges", "Metastase", "Metastase", "Nervenscheiden", "Mesenchymal",
 "Metastase", "Neuroepithelial", "Nervenscheiden", "Neuroepithelial",
 "Neuroepithelial", "Nervenscheiden", "Metastase", "Metastase",
 "Metastase", "Nervenscheiden", "Sonstiges", "Sonstiges", "Metastase",
 "Metastase", "Nervenscheiden", "Metastase", "Metastase", "Neuroepithelial",
 "Sonstiges", "Mesenchymal", "Sonstiges", "Metastase", "Nervenscheiden",
 "Mesenchymal", "Metastase", "Sonstiges", "Nervenscheiden", "Mesenchymal",
 "Metastase", "Sonstiges", "Mesenchymal", "Nervenscheiden", "Nervenscheiden",
 "Sonstiges", "Nervenscheiden", "Neuroepithelial", "Mesenchymal",
 "Metastase", "Mesenchymal", "Mesenchymal", "Metastase", "Sonstiges",
 "Nervenscheiden", "Metastase", "Sonstiges", "Metastase", "Mesenchymal",
 "Metastase", "Nervenscheiden", "Mesenchymal", "Sonstiges", "Nervenscheiden",
 "Neuroepithelial", "Nervenscheiden", "Metastase", "Metastase",
 "Mesenchymal", "Metastase", "Neuroepithelial", "Neuroepithelial",
 "Metastase", "Sonstiges", "Nervenscheiden", "Nervenscheiden", "Metastase",
 "Mesenchymal", "Sonstiges", "Nervenscheiden", "Metastase", "Mesenchymal",
 "Mesenchymal", "Metastase", "Nervenscheiden", "Metastase", "Mesenchymal",
 "Metastase", "Metastase", "Nervenscheiden", "Nervenscheiden", "Mesenchymal",
 "Metastase", "Metastase", "Mesenchymal", "Sonstiges", "Metastase",
 "Metastase", "Mesenchymal", "Metastase", "Nervenscheiden", "Metastase",
 "Metastase", "Metastase", "Mesenchymal", "Metastase", "Nervenscheiden",
 "Nervenscheiden", "Sonstiges", "Neuroepithelial", "Sonstiges", "Metastase",
 "Mesenchymal")
