---
title: "Aufgabe 05"
author: 'Christoph Gastmann | Matrikel: 8112863'
date: "`r Sys.Date()`"
output:
  html_document: default
---

# laden der Pakete
```{r}
library(car)
library(ggplot2)
library(tidyverse)
```

a) W¨ahlen Sie vern¨unftige“ Werte f¨ur die ni und erzeugen Sie reproduzierbar die dazugeh ¨origen Ai!

```{r}
set.seed(42)

k <- 30

n_i <- sample(1:100, k, replace = TRUE)

epsilon_i <- rnorm(k, mean = 0, sd = sqrt(1/2))

A_i <- 10 + 2 * log(n_i) + epsilon_i

data <- data.frame(n_i, A_i)
data
```


b) Fertigen Sie eine Grafik des Graphen der oben beschriebenen Beziehung zwischen a und n an (aber f¨ur reellwertige n ≥ 1) und ¨uberlagern Sie ihr das Streudiagramm der in Teil a erzeugten Wertepaare (ni,Ai) so, dass sie alle sichtbar sind!

```{r}
n_Werte <- seq(1, 100, length.out = 500)
A_Werte <- 10 + 2 * log(n_Werte)

theo_df <- data.frame(n = n_Werte, A = A_Werte)


ggplot() +
  geom_line(data = theo_df, aes(x = n, y = A), color = "blue", size = 1) +
  geom_point(data = data, aes(x = n_i, y = A_i), color = "red") +
  labs(title = "Beziehung zwischen n und A(n) mit simulierten Datenpunkten",
       x = "Anzahl der Werkstücke (n)", y = "Arbeitszeit (A)")
```

```{r}
dev.off()
rm(list = ls())
```

